package com.csa.util;

import java.util.ArrayList;
import java.util.Map;
import com.csa.entity.Bowl;
import com.csa.entity.MatchDetails;
import com.csa.visualization.BattingSegment;
import com.csa.visualization.InningByInningsResults;

public class InningsUtil {

	public static InningByInningsResults generateInningsByInningsResultsFirstInnings(
			MatchDetails match) {

		InningByInningsResults inningsFactorSet = new InningByInningsResults();

		// inningsId will be autoGenerated

		inningsFactorSet.setMatchId(match.getMatchId());
		inningsFactorSet.setFirstInningsOrSecondInnings(1);

		ArrayList<BattingSegment> segmentList = getBattingSegmentList(match
				.getFirstInnings().getDeliveries());

		inningsFactorSet.setNumberOfBattingSegments(segmentList.size());
		inningsFactorSet
				.setAvgMeanRunsInBattingSegment(getMeanRunsInSegment(segmentList));
		inningsFactorSet
				.setAvgRunsInBattingSegment(getAvgRunsInSegment(segmentList));
		inningsFactorSet
				.setAvgPressureFactor(getAvgPressureFactor(segmentList));

		inningsFactorSet.setDotBowlPrerentage(getDotBowlPresentage(match
				.getFirstInnings().getDeliveries()));
		
		//number of Wickets lost in first Innings
		inningsFactorSet.setNumberOfWicketsLost(match.getFirstInnings().getNumberOfWickets());

		// for first innings
		int side = match.getResult().getWonByFirstBatOrSecondBat();
		// team 1 wins
		if (side == 1) {
			inningsFactorSet.setWinOrLoss("win");
		} else if (side == 2) {
			inningsFactorSet.setWinOrLoss("loss");
		} else {
			inningsFactorSet.setWinOrLoss("draw");
		}
		return inningsFactorSet;
	}

	public static InningByInningsResults generateInningsByInningsResultsSecondInnings(
			MatchDetails match) {

		InningByInningsResults inningsFactorSet = new InningByInningsResults();

		// inningsId will be autoGenerated

		inningsFactorSet.setMatchId(match.getMatchId());
		inningsFactorSet.setFirstInningsOrSecondInnings(2);

		ArrayList<BattingSegment> segmentList = getBattingSegmentList(match
				.getSecondInnings().getDeliveries());

		inningsFactorSet.setNumberOfBattingSegments(segmentList.size());
		inningsFactorSet
				.setAvgMeanRunsInBattingSegment(getMeanRunsInSegment(segmentList));
		inningsFactorSet
				.setAvgRunsInBattingSegment(getAvgRunsInSegment(segmentList));
		inningsFactorSet
				.setAvgPressureFactor(getAvgPressureFactor(segmentList));
		// for second innings

		inningsFactorSet.setDotBowlPrerentage(getDotBowlPresentage(match
				.getSecondInnings().getDeliveries()));

		//numberOfWickets lost
		inningsFactorSet.setNumberOfWicketsLost(match.getSecondInnings().getNumberOfWickets());
		
		int side = match.getResult().getWonByFirstBatOrSecondBat();

		// team 1 wins
		if (side == 2) {
			inningsFactorSet.setWinOrLoss("win");
		} else if (side == 1) {
			inningsFactorSet.setWinOrLoss("loss");
		} else {
			inningsFactorSet.setWinOrLoss("draw");
		}
		return inningsFactorSet;
	}

	public static ArrayList<BattingSegment> getBattingSegmentList(
			Map<Integer, com.csa.entity.Bowl> deliveries) {

		ArrayList<BattingSegment> compressSet = new ArrayList<>();
		BattingSegment lastElement;
		for (int i = 1; i < deliveries.size(); i++) {
			if (compressSet.size() != 0) {
				lastElement = compressSet.get(compressSet.size() - 1);
			} else {
				lastElement = new BattingSegment();
				lastElement.setBatsmansName("NO_BATSMAN");
			}

			Bowl bowl = deliveries.get(i);
			String batsman = bowl.getBatsman();

			if (lastElement.getBatsmansName().equals(batsman)) {
				// doNothing
				int currentRunsInTheSegment = lastElement
						.getNumberOfRunsScoredInSegment();
				int currentNumberOfExtrasInSegment = lastElement
						.getNumberOfExtras();
				int currentNumberOfDots = lastElement.getNumberOfDotBowls();
				int currentNumberOfBowls = lastElement.getNumberOfBowls();

				lastElement
						.setNumberOfRunsScoredInSegment(currentRunsInTheSegment
								+ bowl.getRuns());
				lastElement.setNumberOfExtras(currentNumberOfExtrasInSegment
						+ bowl.getExtras());

				if (bowl.getTotalRuns() == 0) {
					lastElement.setNumberOfDotBowls(currentNumberOfDots + 1);
				}
				// this need to be change after find out about type of extras
				lastElement.setNumberOfDotBowls(currentNumberOfBowls + 1);
			} else {
				// create new batting segment
				BattingSegment segment = new BattingSegment();
				segment.setBatsmansName(batsman);
				segment.setNumberOfRunsScoredInSegment(bowl.getRuns());
				segment.setNumberOfExtras(bowl.getExtras());

				if (bowl.getTotalRuns() == 0) {
					segment.setNumberOfDotBowls(1);
				}
				// this need to be change with the extra type
				segment.setNumberOfBowls(1);
				compressSet.add(segment);
			}
		}
		return compressSet;
	}

	public static Double getMeanRunsInSegment(
			ArrayList<BattingSegment> segmentList) {

		Double meanRunsInASegment = 0.0;
		Double avgMeanRunsInASegment = 0.0;
		for (BattingSegment segment : segmentList) {
			int totalRunsInSegment = segment.getNumberOfRunsScoredInSegment();
			int totalBowlsFaceInASegment = segment.getNumberOfBowls();
			meanRunsInASegment = meanRunsInASegment
					+ (totalRunsInSegment / totalBowlsFaceInASegment);
		}
		avgMeanRunsInASegment = meanRunsInASegment / segmentList.size();
		return avgMeanRunsInASegment;
	}

	public static Double getAvgRunsInSegment(
			ArrayList<BattingSegment> segmentList) {

		Double averageRunsInBattingSegment = 0.0;
		int totalRunsInSegment = 0;
		for (BattingSegment segment : segmentList) {
			totalRunsInSegment = totalRunsInSegment
					+ segment.getNumberOfRunsScoredInSegment();
		}

		averageRunsInBattingSegment = totalRunsInSegment
				/ (segmentList.size() + 0.0);

		return averageRunsInBattingSegment;
	}

	public static Double getAvgPressureFactor(
			ArrayList<BattingSegment> segmentList) {

		Double sumofPressreFactor = 0.0;
		Double avgMeanRunsInASegment = 0.0;
		for (BattingSegment segment : segmentList) {
			int totalRunsInSegment = segment.getNumberOfRunsScoredInSegment();
			int totalDotFaceInASegment = segment.getNumberOfDotBowls();
			sumofPressreFactor = sumofPressreFactor + totalRunsInSegment
					/ (totalDotFaceInASegment + 1);
		}
		avgMeanRunsInASegment = sumofPressreFactor / segmentList.size();

		return avgMeanRunsInASegment;
	}

	public static Double getDotBowlPresentage(
			Map<Integer, com.csa.entity.Bowl> deliveries) {
		int numberOfDotBowls = 0;
		Double dotBowlPresentage = 0.0;
		for (int i = 1; i < deliveries.size(); i++) {
			Bowl bowl = deliveries.get(i);
			if (bowl.getTotalRuns() == 0) {
				numberOfDotBowls++;
			}
		}
		dotBowlPresentage = numberOfDotBowls * (100.0) / deliveries.size();
		return dotBowlPresentage;
	}
	
	
}
